---

- name: enable epel repository
  command: "/usr/bin/dnf -y install {{ epel_repo }}"
  become: yes

- name: enable powertools repository
  command: "/usr/bin/dnf config-manager --set-enabled powertools"
  become: yes