---

- name: configurando el repositorio de docker
  command: "/usr/bin/dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  become: yes

- name: instalando docker-ce
  dnf:
    name: "{{ docker_rpms }}"
    state: present
  become: yes

- name: configurando el arranque de docker
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes
